"""Protocols that keep model providers replaceable."""

from typing import Any, Dict, Optional, Protocol


class ModelProvider(Protocol):
    def available(self) -> bool: ...
    def call(self, prompt: str, **kwargs: Any) -> Any: ...


class MemoryStore(Protocol):
    def add_text(self, text: str, **kwargs: Any) -> None: ...
    def search_text(self, query: str, k: int = 5, kind: Optional[str] = None) -> list: ...
    def knowledge(self, query: str, limit: int = 3) -> list: ...
    def purge_tasks(self, keep: int = 1000) -> int: ...


class Notifier(Protocol):
    def send(self, text: str, **kwargs: Any) -> None: ...


class Capability(Protocol):
    def __call__(self, args: Dict[str, Any]) -> Any: ...


class EventBusProvider(Protocol):
    def publish(self, topic: str, payload: Dict[str, Any], **kwargs: Any) -> Any: ...
    def consume(self, limit: int = 10) -> list: ...


class SchedulerProvider(Protocol):
    def schedule(self, topic: str, payload: Dict[str, Any], **kwargs: Any) -> Any: ...
    def run_once(self) -> int: ...
    def stop(self) -> None: ...
