const messages=document.getElementById('messages'),input=document.getElementById('input'),send=document.getElementById('send'),clearBtn=document.getElementById('clear'),downloadBtn=document.getElementById('download'),langSel=document.getElementById('lang');
    function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('ada_csrf='))?.split('=').slice(1).join('=')||''}
    function escapeHtml(value){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
    function inlineMarkdown(value){let out=escapeHtml(value);out=out.replace(/`([^`]+)`/g,'<code>$1</code>');out=out.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/__([^_]+)__/g,'<strong>$1</strong>');out=out.replace(/~~([^~]+)~~/g,'<del>$1</del>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/_([^_]+)_/g,'<em>$1</em>');out=out.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>');return out}
    function markdownToHtml(markdown){const lines=String(markdown??'').replace(/\r\n?/g,'\n').split('\n');let html='',paragraph=[],list=null,inCode=false,code=[];
      const flushParagraph=()=>{if(paragraph.length){html+='<p>'+paragraph.map(inlineMarkdown).join('<br>')+'</p>';paragraph=[]}};
      const closeList=()=>{if(list){html+='</'+list+'>';list=null}};
      for(let i=0;i<lines.length;i++){const line=lines[i],trim=line.trim();
        if(trim.startsWith('```')){if(inCode){html+='<pre><code>'+escapeHtml(code.join('\n'))+'</code></pre>';code=[];inCode=false}else{flushParagraph();closeList();inCode=true}continue}
        if(inCode){code.push(line);continue}
        const next=lines[i+1]?.trim()||'';
        if(trim.startsWith('|')&&/^\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?$/.test(next)){flushParagraph();closeList();const headers=trim.replace(/^\||\|$/g,'').split('|').map(x=>inlineMarkdown(x.trim()));i+=2;const rows=[];while(i<lines.length&&lines[i].trim().startsWith('|')){rows.push(lines[i].trim().replace(/^\||\|$/g,'').split('|').map(x=>inlineMarkdown(x.trim())));i++}i--;html+='<table><thead><tr>'+headers.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table>';continue}
        let match=trim.match(/^(#{1,3})\s+(.+)/);if(match){flushParagraph();closeList();html+='<h'+match[1].length+'>'+inlineMarkdown(match[2])+'</h'+match[1].length+'>';continue}
        if(/^[-*_]{3,}$/.test(trim)){flushParagraph();closeList();html+='<hr>';continue}
        match=trim.match(/^[-*+]\s+(.+)/);if(match){flushParagraph();if(list!=='ul'){closeList();html+='<ul>';list='ul'}html+='<li>'+inlineMarkdown(match[1])+'</li>';continue}
        match=trim.match(/^\d+[.)]\s+(.+)/);if(match){flushParagraph();if(list!=='ol'){closeList();html+='<ol>';list='ol'}html+='<li>'+inlineMarkdown(match[1])+'</li>';continue}
        if(trim.startsWith('>')){flushParagraph();closeList();html+='<blockquote>'+inlineMarkdown(trim.replace(/^>\s?/,' '))+'</blockquote>';continue}
        if(!trim){flushParagraph();closeList();continue}paragraph.push(line)
      }if(inCode)html+='<pre><code>'+escapeHtml(code.join('\n'))+'</code></pre>';flushParagraph();closeList();return html||'<p></p>'}
    function readableMessage(text){try{const value=JSON.parse(text);if(value.workflow!=='photo_review')return text;const t=value.technical||{},s=value.semantic||{},r=value.review||{},f=t.focus||{},e=t.exposure||{},c=t.composition||{},m=s.session_match||{};const score=v=>v===undefined?'—':v+'/10';const confidence=typeof m.confidence==='number'?(Math.round((m.confidence<=1?m.confidence*100:m.confidence))+'%'):(m.confidence||'—');let out='# Análisis fotográfico\n\n';out+='## Veredicto: '+(r.recommendation||'revisar')+' · '+score(t.overall_score)+'\n\n';out+='| Área | Puntuación | Lectura |\n|---|---:|---|\n';out+='| Enfoque | '+score(f.score)+' | '+(f.score<5?'Nitidez limitada; revisar foco o trepidación':'Nitidez aceptable')+' |\n';out+='| Exposición | '+score(e.score)+' | '+(e.score<5?'Subexpuesta o con sombras densas':'Equilibrada')+' |\n';out+='| Composición técnica | '+score(c.score)+' | Evaluación técnica |\n\n';if(s.subject)out+='## Lectura de la escena\n\n**Sujeto y contexto:** '+s.subject+'\n\n';if(s.style)out+='**Estilo:** '+s.style+'\n\n';if(s.photographer_feedback)out+='## Devolución como fotógrafo\n\n'+s.photographer_feedback+'\n\n';if(m.confidence)out+='**Coincidencia con la sesión:** '+confidence+'\n\n'+(m.reason||'')+'\n\n';if(r.strengths?.length)out+='**Puntos fuertes**\n\n'+r.strengths.map(x=>'- '+x).join('\n')+'\n\n';if(r.issues?.length)out+='**A revisar**\n\n'+r.issues.map(x=>'- '+x).join('\n')+'\n\n';return out.trim()}catch(err){return text}}
    function renderBody(element,text){const readable=readableMessage(String(text??''));element.dataset.markdown=readable;element.innerHTML=markdownToHtml(readable)}
    function add(role,text){document.getElementById('empty')?.remove();const row=document.createElement('div');row.className='row '+role;const bubble=document.createElement('div');bubble.className='bubble';const meta=document.createElement('div');meta.className='meta';meta.textContent=role==='user'?'Vos':'ADA';const body=document.createElement('div');renderBody(body,text);bubble.append(meta,body);row.append(bubble);messages.append(row);messages.scrollTop=messages.scrollHeight;return row}
    async function submit(){const text=input.value.trim();if(!text||send.disabled)return;add('user',text);input.value='';send.disabled=true;try{const resp=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json','X-ADA-Token':csrf()},body:JSON.stringify({message:text,lang:langSel.value})});if(!resp.ok)throw new Error('HTTP '+resp.status);const reader=resp.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});const blocks=buffer.split('\n\n');buffer=blocks.pop();for(const block of blocks){const line=block.split('\n').find(item=>item.startsWith('data: '));if(!line)continue;const event=block.match(/^event: (.+)$/m)?.[1]||'reply';const payload=JSON.parse(line.slice(6));if(event==='status'||event==='reply'||event==='error')add('bot',payload.text||'(sin respuesta)')}}await loadConversation()}catch(err){add('bot','No pude conectar con ADA: '+err.message)}finally{send.disabled=false;input.focus()}}
    function renderConversation(items){messages.innerHTML='';if(!items?.length){messages.innerHTML='<div class="empty" id="empty"><h1>¿Qué hacemos hoy?</h1><p>Podés preguntarme algo, pedirme un análisis o enseñarme un procedimiento.</p></div>';return}items.forEach(item=>add(item.role==='user'?'user':'bot',item.text))}
    async function loadConversation(){try{const resp=await fetch('/api/conversation',{cache:'no-store'});const data=await resp.json();renderConversation(data.messages||[])}catch(err){console.warn('No se pudo cargar el historial',err)}}
    async function clearConversation(){await fetch('/api/conversation',{method:'DELETE',headers:{'Content-Type':'application/json','X-ADA-Token':csrf()}});messages.innerHTML='<div class="empty" id="empty"><h1>¿Qué hacemos hoy?</h1><p>Podés preguntarme algo, pedirme un análisis o enseñarme un procedimiento.</p></div>'}
    function downloadMarkdown(){const rows=[...messages.querySelectorAll('.row')];let md='# Conversación con ADA\n\n';if(!rows.length)md+='_(Sin mensajes todavía.)_\n';rows.forEach(row=>{const role=row.classList.contains('user')?'Vos':'ADA';const body=row.querySelector('.bubble [data-markdown]')?.dataset.markdown||'';md+=`## ${role}\n\n${body}\n\n`});const blob=new Blob([md],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ada-conversacion-${new Date().toISOString().slice(0,10)}.md`;a.click();URL.revokeObjectURL(url)}
    send.onclick=submit;downloadBtn.onclick=downloadMarkdown;clearBtn.onclick=clearConversation;input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}});loadConversation();input.focus();

